### ISSUE TITLE
Other Declink cards working?

### ISSUE THREAD

**Issue by mr-berndt** [defl/videoprocessor#1]
Hello, spending 500 € just for a test is a bit much, so I wonder if the seemingly very similar Deckling Mini Recorder 4k card might work just as well. https://www.mediatec.de/postproduktion/io-interfaces/blackmagic-decklink-mini-recorder-4k?gclid=Cj0KCQjw16KFBhCgARIsALB0g8KGXsF0LjMyVHmkgJG-p-gXG48X69Glu6aE9YediO8kmNCFAbJt2pEaAkeNEALw_wcB

Thx and greetings!

**Comment by defl** [comment]
See main README of this project at https://github.com/defl/videoprocessor under heading capture cards. The mini 4k recorder works perfectly but might cause you a bit of work if your menus are in 4k60. It's the card I use.

**Comment by mr-berndt** [comment]
My bad. i wrongly understood, that there is a "small" card with 4 inputs claimed as "tested an working". THat was the "big" card, though.

Let me ask you one more question: How is synchronisation of the cards HDMI input and the GPUs HDMI output achieved? This seems somewhat important.

**Comment by defl** [comment]
You can get a framerate sync as madVR can set your output video mode to the input. There is no guarantee on processing-delay, so that will drift. At the end of the day the HDMI input rate is what feeds frames to the system, so it's hard to underrun/overrun more than a frame. If you have exact measurements around this I'd be happy to learn more though I wouldn't know how to fix it it it turns out to be an issue at this time.

**Comment by mr-berndt** [comment]
OK, so it is free running after all. Do you experience any issues with that, visually?

**Comment by defl** [comment]
At this moment I suspect yes because I'm not clocking the frames on the capture card clock but the system clock when the frame enters the directshow graph. There's some microstutter that I'm seeing which I don't like and I think it's that. High on the prio list to move the clock to the card hardware clock so that the graph can show them at the right time.

**Comment by mr-berndt** [comment]
OK, thx for clearing that up. In this case I'd rather wait and see if you can manage to sync the two streams somehow. For me it would not really give a benefit, if the streams have any kind of stutter, may it even be very small.
