### ISSUE TITLE
Hdr data doesn't show in videoprocessor anymore

### ISSUE THREAD

**Issue by Pinoginooo** [defl/videoprocessor#2]
Hi Dennis,

Thanks for your work, Videoprocessor is getting better and better.

I had an issue with Videoprocessor: it was working fine up till I had to reinstall windows 10, after I reconfigured all the data in the tab HDR (in the video processor gui color coordinates, maxfall and maxcll) no longer appear .

I don't know if it is related, but these information are no longer available in the vertex 2 osd. The source of these information is the vertex (like with the filter) or they should be extracted from the video stream?

Thanks if you have any suggestion

**Comment by defl** [comment]
Hi Pinoginooo,

Unlike the filter and the import through the Python script, VideoProcessor works solely with the info embedded in the video stream (HDMI most often). If the Vertex2 is not showing any HDR (what does it show exactly?) then there will be no HDR and in that sense VideoProcessor is doing exacly what you'd expect.

Are you sure the upstream is sending HDR? Maybe take a good look at the Vertex2 config to check if everything is set as you'd expect? Also check your source if it says it's sending HDR, very often that's quite clear but it's highly source dependent. Because normally these things are just the hardware EDID talking to eachother and the Vertex is one of the few devices which can successfully alter it.

**Comment by Pinoginooo** [comment]
Sorry for bothering you, it was my fault, i just found the issue: I was sending lldv, so the videostream wasn't true hdr and consequently videoprocessor wasn't able to determine the correct data (and for the same reason vertex wasn't showing them). 

I would like to ask you if in the future (or maybe is already possible right now but I don't know how to do it) would be possible to send videoprocessor a 4:2:0 p010 videostream in order to have madvr to do the chroma upsampling (actually I cannot change apple tv to send 4:2:2)? 

Thanks again for your work video processor and metadata injection filter are both great.
